[package]
name = "test_utils"
version = "0.1.0"
authors = ["Calimero Limited <info@calimero.network>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
types = { path = "../types" }
utils = { path = "../utils" }
base64 = "0.13"
near-units = "0.2.0"
near-sdk = "4.0.0"
